### ISSUE TITLE
Custom Element Does Not Exist After HASS Update to 2023.10.1

### ISSUE THREAD

**Issue by birwin88** [isabellaalstrom/lovelace-grocy-chores-card#130] opened 2023-10-12 12:57 UTC
I upgraded from 2023.09.3 to 2023.10.1 and it seems to have broken the card

I uninstalled and reinstalled the card + card tools with HACS in an attempt to get it working again.  

Here's my card's YAML:

type: custom:grocy-chores-card
entity: sensor.grocy_chores
title: Chores
show_quantity: 5
show_assigned: true
show_overflow: true
show_chores_without_due: true
show_tasks_without_due: true
use_icons: true
use_long_date: true
due_in_days_threshold: 7
use_24_hours: true
hide_text_with_no_data: true

I get the error: Custom element doesn't exist: grocy-chores-card.

If I try and use the YAML from the example in the documentation I get the error No Card Type Configured:

**Comment by sehnugr** [comment] 2023-10-12 14:19
I got this same issue

**Comment by karwosts** [comment] 2023-10-12 14:21
Duplicate of #94

**Closed** 2023-10-19 13:18 UTC
