### ISSUE TITLE
Custom element doesn't exist: grocy-chores-card.

### ISSUE THREAD

**Issue by Greenphlem** [isabellaalstrom/lovelace-grocy-chores-card#94] opened 2023-04-04 18:11 UTC
Hello, 

Just today, my Grocy card stopped working giving me the error on my Lovelace dashboard: `Custom element doesn't exist: grocy-chores-card `

I see the card's resource under Dashboards > Resources but it is not seeming to load. 

Here's my card YAML: 

```type: custom:grocy-chores-card
entity:
  - sensor.grocy_chores
title: Today's Chores
show_quantity: 3
show_days: 0
user_id: 2
show_assigned: true
show_overflow: true
show_chores_without_due: true
show_tasks_without_due: true
use_icons: true
date_due_threshold: 0
show_last_tracked: false

**Comment by dgrnbrg** [comment] 2023-04-23 14:44
This happens when the JavaScript host unpkg has a temporary outage. It hits me often too, and it’s annoying. Maybe someone with experience packaging JS could make a build that pulls this card’s dependencies to be fully local?

**Comment by grzech1983** [comment] 2023-10-10 08:11
Hello,

I would like to return to this bug. Currently this is not related to unpkg outage but some syntax error error:

`SyntaxError: unknown: Support for the experimental syntax 'logicalAssignment' isn't currently enabled (6:629):`

https://unpkg.com/lit-element@4.0.0/lit-element.js?module

https://unpkg.com/@lit/reactive-element@2.0.0/reactive-element.js?module

**Comment by HAuser1234** [comment] 2023-10-10 10:01
Hi,
I have the same Issue. even with Version 3.6
Yesterday everything worked just fine. Now the card only displays the error: "Custom element doesn't "
I tried reinstalling it clearing browser chache. Nothing worked!
Thanks

**Comment by rickgardner077** [comment] 2023-10-10 12:40
Same thing happened to me today on v3.8.1 of grocy-chores-card

**Comment by cooperised** [comment] 2023-10-10 12:59
I also started receiving this error today. I was on 3.6.1 and had changed nothing, but I tried updating to 3.8.1 to see if anything changed and it did not. Something server-side somewhere has broken today, but I'm not knowledgeable enough to know what...

**Comment by isabellaalstrom** [comment] 2023-10-10 13:16
I am sorry to hear that, but unfortunately I don't have the time to work on a fix. If someone has the time and knowledge and makes a pr I will look at it.

**Comment by sagresbier** [comment] 2023-10-10 14:11
Same Error to me since yesterday.
Is there any working version or workaround for HA-Docker?

**Comment by poxin13** [comment] 2023-10-10 15:20
Also running into this issue again, would be great if the JS resource could be used locally but I'm not familiar enough how to rework it to do so.

**Comment by HAuser1234** [comment] 2023-10-10 15:42
> The steps I posted above to create a rolled up card still work if you want to fix the issue locally, and will remove the cloud dependency on unpkg.
> 
> [#94 (comment)](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/issues/94#issuecomment-1520217893)
> 
> It's a bit technical though.

I have tried these steps. It didnt compile because of an error: SECOND_ROUNDING_EPSILON = 0.000_000_1;
could you please share your modified grocy-chores-card.js ?

**Comment by karwosts** [comment] 2023-10-10 15:46
[grocy-chores-card-pkg.zip](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/files/12859128/grocy-chores-card-pkg.zip)

I've attached the card I compiled, I don't recall exactly what version it is from. 

Generally I would suggest not installing .js files from randos on the internet, but it's here at your own risk :grin:

**Comment by poxin13** [comment] 2023-10-10 15:53
Worked brilliantly, thanks!

**Comment by cooperised** [comment] 2023-10-10 15:53
@karwosts Do these steps not depend on a working version of lit-element being available on unpkg?

**Comment by HAuser1234** [comment] 2023-10-10 15:55
> @karwosts Do these steps not depend on a working version of lit-element being available on unpkg?
I think this is where the error might come from.

> Generally I would suggest not installing .js files from randos on the internet, but it's here at your own risk 😁
ok than i'll wait😂 but isn't the original github file also from the intenet?

**Comment by poxin13** [comment] 2023-10-10 16:06
Haven't tested but what about simply using another CDN instead of unpkg for the time being:

```
< import {html, LitElement, nothing} from "https://esm.run/lit";
< import {DateTime} from "https://esm.run/luxon@3.0.3";
```

**Comment by HAuser1234** [comment] 2023-10-10 16:10
Just as a info compiling works just download Node.js for windows and do not use WSL.
and the new pointer is /local/community/  instead of hacksfiles

**Comment by cooperised** [comment] 2023-10-10 16:42
Really appreciate the info on a local build, but of course a "fix" that involves everyone compiling their own instead of installing from HACS is not really optimal. Changing the CDN as suggested by @poxin13 would seem like a good idea, is anyone able to test and maybe create a PR?

**Comment by HAuser1234** [comment] 2023-10-10 16:51
just one last thing. Should the goal in the end be to be reliant on online services? A compleatly local card loads much faster, works without internet and is much more futureproof.

**Comment by poxin13** [comment] 2023-10-10 16:55
> just one last thing. Should the goal in the end be to be reliant on online services? A compleatly local card loads much faster, works without internet and is much more futureproof. I would rather prefer a local only solution as a default solution

I agree with this

**Comment by karwosts** [comment] 2023-10-10 16:57
I saw that @isabellaalstrom started a branch a couple years ago experimenting with card rollup, but it doesn't look like that was ever fully pursued. 

https://github.com/isabellaalstrom/lovelace-grocy-chores-card/tree/rollup

Isabella, just curious do you recall what happened there, was it unsatisfactory, or did you just never have time to work on it? 

I agree that local is so much nicer. When I use local card it is always loaded instantly, versus always a 1-second late card popin from the CDN (or occasional random errors if it is delayed more than 2s).

**Comment by HAuser1234** [comment] 2023-10-10 16:59
I compiled the newest version of the card and it works perfectly. I see no drawbacks so far.

**Comment by cooperised** [comment] 2023-10-10 18:57
Agree that local is nicer.  Changing CDN would be a quick fix in the interim though - until then this card is going to be broken for everyone unless something changes on unpkg.

For an automated fully local build, I don't know enough about GitHub's CI/CD pipeline to be able to automate a local build - I've done things like this on GitLab but not over here.  Anyone want to have a go?

**Comment by karwosts** [comment] 2023-10-11 00:27
I haven't messed with this stuff too much before, but I tried playing with a CI pipeline here to build the packaged version on release. It seems to work, and when I download the card in the bundle's assets, it works for me. 

https://github.com/karwosts/lovelace-grocy-chores-card/releases/tag/v0.0.2

https://github.com/karwosts/lovelace-grocy-chores-card/releases/download/v0.0.2/grocy-chores-card-pkg.js

Maybe this will be useful.

**Comment by cooperised** [comment] 2023-10-11 15:26
That's excellent. Any chance of putting in a PR to have it added to the
main repo, and a new release created? That would fix the problem for
everyone by just upgrading from HACS.

**Comment by karwosts** [comment] 2023-10-11 15:30
> That's excellent. Any chance of putting in a PR to have it added to the main repo, and a new release created? That would fix the problem for everyone by just upgrading from HACS.


I'm willing to collaborate to help this effort, but first would like some feedback from the repository owner if that's a direction she wants to go in. 

I imagine it could be a disruptive change, and I'm not sure how hacs will treat switching from a source file to a released asset file.

**Comment by isabellaalstrom** [comment] 2023-10-11 17:12
> > That's excellent. Any chance of putting in a PR to have it added to the main repo, and a new release created? That would fix the problem for everyone by just upgrading from HACS.
> 
> 
> 
> 
> 
> I'm willing to collaborate to help this effort, but first would like some feedback from the repository owner if that's a direction she wants to go in. 
> 
> 
> 
> I imagine it could be a disruptive change, and I'm not sure how hacs will treat switching from a source file to a released asset file. 

Go for it, I think it's the best way forward. We'll see how hacs handles it

**Comment by cdouet** [comment] 2023-10-13 20:10
> I haven't messed with this stuff too much before, but I tried playing with a CI pipeline here to build the packaged version on release. It seems to work, and when I download the card in the bundle's assets, it works for me.
> 
> https://github.com/karwosts/lovelace-grocy-chores-card/releases/tag/v0.0.2
> 
> https://github.com/karwosts/lovelace-grocy-chores-card/releases/download/v0.0.2/grocy-chores-card-pkg.js
> 
> Maybe this will be useful.
> 
> This is also installable via HACS: https://github.com/karwosts/lovelace-grocy-chores-card

Installing this repo and card has worked for me.
Thanks a lot!

**Comment by rickgardner077** [comment] 2023-10-13 21:19
> > I haven't messed with this stuff too much before, but I tried playing with a CI pipeline here to build the packaged version on release. It seems to work, and when I download the card in the bundle's assets, it works for me.
> > 
> > https://github.com/karwosts/lovelace-grocy-chores-card/releases/tag/v0.0.2
> > 
> > https://github.com/karwosts/lovelace-grocy-chores-card/releases/download/v0.0.2/grocy-chores-card-pkg.js
> > 
> > Maybe this will be useful.
> > 
> > This is also installable via HACS: https://github.com/karwosts/lovelace-grocy-chores-card
> 
> Installing this repo and card has worked for me.
> Thanks a lot!

Installed this via HACS, the card is working again. Great work

**Comment by Medicalmusings** [comment] 2023-10-13 21:49
Brilliant brilliant brilliant - thank you.

**Comment by sagresbier** [comment] 2023-10-14 09:00
Works brilliant. 
@karwosts @isabellaalstrom 
Thanks for your work.

**Comment by Greenphlem** [comment] 2023-10-14 19:08
Any chance this gets merged into master?

**Comment by B4dC4rd** [comment] 2023-10-16 22:51
@karwosts Great stuff mate, cheers to the OG @isabellaalstrom

**Comment by Cloudhidden** [comment] 2023-10-18 23:13
> > > I haven't messed with this stuff too much before, but I tried playing with a CI pipeline here to build the packaged version on release. It seems to work, and when I download the card in the bundle's assets, it works for me.
> > > https://github.com/karwosts/lovelace-grocy-chores-card/releases/tag/v0.0.2
> > > https://github.com/karwosts/lovelace-grocy-chores-card/releases/download/v0.0.2/grocy-chores-card-pkg.js
> > > Maybe this will be useful.
> > > This is also installable via HACS: https://github.com/karwosts/lovelace-grocy-chores-card
> > 
> > 
> > Installing this repo and card has worked for me.
> > Thanks a lot!
> 
> Installed this via HACS, the card is working again. Great work

How did you install via HACS? The link in karwosts repo doesn't work and I can't find his repo by searching in HACS. :(

**Comment by karwosts** [comment] 2023-10-19 13:08
Ok I just released v3.8.2 as a HACS beta, it should fix the problem. Anyone can confirm?

**Comment by PurelyNicole** [comment] 2023-10-19 13:13
@karwosts Confirmed working for me.

**Comment by AlesZurek** [comment] 2023-10-19 13:39
@karwosts works for me

**Comment by schwartzpub** [comment] 2023-10-19 13:40
@karwosts working here as well. Appears a new bug may be introduced but still trying to confirm it's not my own mistake somewhere:

![image](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/assets/5823949/aa9da5c6-ce8e-4921-b123-c8a17abd1e46)

Changing show_days config to numerical bool removes the error.

**Comment by karwosts** [comment] 2023-10-19 13:48
There were a couple feature changes since the last functional release, so there could be some changes. Looks like `show_days` is not supposed to be a boolean as per the docs though. 



That said I think this issue can be closed now, and the resolution is to update to v3.8.2.

**Closed by karwosts** 2023-10-19 13:48 UTC
Labels: bug
