### ISSUE TITLE
Show more now shows less

### ISSUE THREAD

**Issue by larsalthof** [isabellaalstrom/lovelace-grocy-chores-card#115] opened 2023-04-28 04:24 UTC
When i click “Show more” I used to see the remaining chores, now it hides the all

**Comment by karwosts** [comment] 2023-04-28 12:36
Most likely duplicate of #107 ; suggest trying the latest beta version from a few days ago.

**Comment by karwosts** [comment] 2023-10-19 14:06
Believe this was resolved, please comment if you're still seeing an issue in the latest version.

**Closed by karwosts** 2023-10-19 14:06 UTC
Labels: bug, duplicate
